---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen-0725
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-0725 
  name: codegen-0725
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi